### PR TITLE
Latlong

### PR DESCRIPTION
**Pull request by js223kz**

### CODE REVIEW

**Comment by fyrkant** [comment]
I don't think that it's good to merge failing builds, and I'm not only saying it to be an asshole but if I remember correctly the auto-deploy system that @rk222ev put in place only deploys builds that are passing the tests so the code merged in the master branch won't be the code deployed right now, which might be kind of confusing.

**Comment by rpkarlsson** [comment]
Ah, sorry.  I may have been very bad at communicating the intention and rules surrounding the auto deploy. 

@mw222rs is correct. Only code with passing tests will auto deploy. So the general idea is to develop on branches. When all is ready and correct, merge with master. Master is always supposed to pass its tests and to build correctly.

Should we have a wish to alter this work flow we need to find a different strategy. To enable easy testing between the server and the client project.

I see that the commits state that the tests should be passing. Do we have passing local test runs and failing travis test runs?

**Comment by Angamanga** [comment]
@rk222ev Yes, that is true, we have local passing tests which fails with Travis. Maybe we can take a look today, I think it  has to do with the paths in some way.

**Comment by Angamanga** [comment]
And its no problem with the work flow... we'll continue with that as it is! We just had to sort our code out and sync everything and the only time we had to do that was yesterday evening. And since it seemed to be something with Travis and not with local tests, we thought that it was better to get the work done :+1:

**Comment by rpkarlsson** [comment]
Ah I see. =)

Suspected that the problem was a failure to communicate the intent and rules surrounding the autodeploy from my side. Glad to see that wasn't the case.

Communicating over the internet is hard!

Threw a quick glance at the travis tests. I suspect the problem is that app/models/User.js
is named with an uppercase U. I believe travis running on linux requires the file name to be lowercase since the import statement (require or whats its name) is done in lowercase.

Try renaming User.js to user.js.

**Comment by js223kz** [comment]
I've tried renaming the file but get an error that file with that name
already exists. Will try again now when everything is up to date.
Den 18 feb 2016 09:24 skrev "Robin Karlsson" notifications@github.com:

**Pull request merged**
